AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS ECS POC Infrastructure

######
####### PARAMETERS #########
######

Parameters:
  GitHubOwner:
    Type: String
    Default: gutkedu
  GitHubRepo:
    Type: String
    Default: aws-ecs-poc
    
######
####### GLOBALS #########
######

Globals:
  Function:
    Timeout: 5

######
####### REPOSITORIES #########
######

Resources:
  ApiEcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: aws-ecs-poc-api
      ImageScanningConfiguration:
        ScanOnPush: true

  WorkerEcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: aws-ecs-poc-worker
      ImageScanningConfiguration:
        ScanOnPush: true

######
####### IAM #########
######

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser
      Policies:
        - PolicyName: CodeBuildPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

######
####### ECS #########
######

  EcsCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: aws-ecs-poc-cluster

  EcsTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  ApiTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ApiSqsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource: !GetAtt SqsQueue.Arn

  WorkerTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: WorkerSqsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt SqsQueue.Arn

  ApiTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: aws-ecs-poc-api
      Cpu: "256"
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt EcsTaskExecutionRole.Arn
      TaskRoleArn: !GetAtt ApiTaskRole.Arn
      ContainerDefinitions:
        - Name: api
          Image: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/aws-ecs-poc-api:latest'
          PortMappings:
            - ContainerPort: 3000
              Protocol: tcp
          Environment:
            - Name: SQS_QUEUE_URL
              Value: !Ref SqsQueue
            - Name: AWS_REGION
              Value: !Ref AWS::Region
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/aws-ecs-poc-api
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs

  WorkerTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: aws-ecs-poc-worker
      Cpu: "256"
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt EcsTaskExecutionRole.Arn
      TaskRoleArn: !GetAtt WorkerTaskRole.Arn
      ContainerDefinitions:
        - Name: worker
          Image: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/aws-ecs-poc-worker:latest'
          Environment:
            - Name: SQS_QUEUE_URL
              Value: !Ref SqsQueue
            - Name: AWS_REGION
              Value: !Ref AWS::Region
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/aws-ecs-poc-worker
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs

  ApiService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: aws-ecs-poc-api-service
      Cluster: !Ref EcsCluster
      TaskDefinition: !Ref ApiTaskDefinition
      DesiredCount: 0
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !Ref EcsSecurityGroup
          Subnets:
            - !Ref PublicSubnet1
            - !Ref PublicSubnet2

  WorkerService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: aws-ecs-poc-worker-service
      Cluster: !Ref EcsCluster
      TaskDefinition: !Ref WorkerTaskDefinition
      DesiredCount: 0
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !Ref EcsSecurityGroup
          Subnets:
            - !Ref PublicSubnet1
            - !Ref PublicSubnet2

  WorkerScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    DependsOn: WorkerService
    Properties:
      MinCapacity: 0
      MaxCapacity: 10
      ResourceId: service/aws-ecs-poc-cluster/aws-ecs-poc-worker-service
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs
      RoleARN: !GetAtt AutoScalingRole.Arn

  WorkerScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    DependsOn: WorkerScalableTarget
    Properties:
      PolicyName: WorkerScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref WorkerScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 1.0
        PredefinedMetricSpecification:
          PredefinedMetricType: SQSQueueMessagesVisiblePerTask
          ResourceLabel: !Sub ${SqsQueue.QueueName}
        ScaleInCooldown: 60
        ScaleOutCooldown: 60

  WorkerScaleOutPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    DependsOn: WorkerScalableTarget
    Properties:
      PolicyName: WorkerScaleOutPolicy
      PolicyType: StepScaling
      ScalingTargetId: !Ref WorkerScalableTarget
      StepScalingPolicyConfiguration:
        AdjustmentType: ChangeInCapacity
        MetricAggregationType: Average
        StepAdjustments:
          - MetricIntervalLowerBound: 0
            ScalingAdjustment: 1

  WorkerScaleInPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    DependsOn: WorkerScalableTarget
    Properties:
      PolicyName: WorkerScaleInPolicy
      PolicyType: StepScaling
      ScalingTargetId: !Ref WorkerScalableTarget
      StepScalingPolicyConfiguration:
        AdjustmentType: ExactCapacity
        MetricAggregationType: Average
        StepAdjustments:
          - MetricIntervalLowerBound: 0
            MetricIntervalUpperBound: 0
            ScalingAdjustment: 0

  ScaleOutAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: WorkerScaleOutAlarm
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Dimensions:
        - Name: QueueName
          Value: !GetAtt SqsQueue.QueueName
      Period: 60
      Statistic: Average
      Threshold: 1
      AlarmActions:
        - !Ref WorkerScaleOutPolicy

  ScaleInAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: WorkerScaleInAlarm
      ComparisonOperator: LessThanThreshold
      EvaluationPeriods: 5
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Dimensions:
        - Name: QueueName
          Value: !GetAtt SqsQueue.QueueName
      Period: 60
      Statistic: Average
      Threshold: 1
      AlarmActions:
        - !Ref WorkerScaleInPolicy

  AutoScalingRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: application-autoscaling.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

######
####### NETWORKING #########
######

  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [1, !GetAZs '']
      MapPublicIpOnLaunch: true

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  GatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref Vpc
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  Subnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  Subnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  EcsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for ECS services
      VpcId: !Ref Vpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0

######
####### SQS #########
######

  SqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: aws-ecs-poc-queue
      VisibilityTimeout: 30
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SqsDlq.Arn
        maxReceiveCount: 3

  SqsDlq:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: aws-ecs-poc-dlq

  ApiLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/aws-ecs-poc-api
      RetentionInDays: 30

  WorkerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/aws-ecs-poc-worker
      RetentionInDays: 30

  ApiCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: aws-ecs-poc-api-build
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Value: !Ref AWS::Region
          - Name: API_REPO_URI
            Value: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/aws-ecs-poc-api'
      Source:
        Type: GITHUB
        Location: !Sub 'https://github.com/${GitHubOwner}/${GitHubRepo}.git'
        GitCloneDepth: 1
        BuildSpec: backend/api/buildspec.yml

  WorkerCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: aws-ecs-poc-worker-build
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Value: !Ref AWS::Region
          - Name: WORKER_REPO_URI
            Value: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/aws-ecs-poc-worker'
      Source:
        Type: GITHUB
        Location: !Sub 'https://github.com/${GitHubOwner}/${GitHubRepo}.git'
        GitCloneDepth: 1
        BuildSpec: backend/worker/buildspec.yml


######
####### OUTPUTS #########
######

Outputs:
  ApiRepositoryUri:
    Description: URI of the API ECR repository
    Value: !GetAtt ApiEcrRepository.RepositoryUri
  WorkerRepositoryUri:
    Description: URI of the Worker ECR repository
    Value: !GetAtt WorkerEcrRepository.RepositoryUri
  SqsQueueUrl:
    Description: URL of the SQS queue
    Value: !Ref SqsQueue
  SqsDlqUrl:
    Description: URL of the SQS DLQ
    Value: !Ref SqsDlq
